on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Go-Bindata Dummy
      run: |
        go get -u github.com/go-bindata/go-bindata/...
        mkdir -p ./build/tor
        touch ./build/tor/tor
        go-bindata -nometadata -nocompress -o ./internal/bindata/bindata.go -pkg bindata ./build/tor/tor
    - name: Test
      run: go test ./...